# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField(verbose_name='Invoice number')),
                ('purchase_date', models.DateTimeField(verbose_name='Date of purchase')),
                ('product', models.CharField(max_length=400, verbose_name='Product')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('document', models.IntegerField(primary_key=True, serialize=False, verbose_name='Document')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.AddField(
            model_name='purchases',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Users'),
        ),
    ]
