# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice', models.IntegerField(primary_key=True, serialize=False, verbose_name='Invoice number')),
                ('invoice_date', models.DateTimeField(verbose_name='Date of purchase')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='document',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Invoices'),
        ),
    ]
