# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0002_auto_20170514_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400, verbose_name='Value')),
            ],
        ),
    ]
